services:
  brmusic-frontend:
    build: .
    container_name: brmusic-frontend
    image: ernandopaiva/brmusic-frontend:1.0.0
    ports:
      - "3002:3002"
    restart: always
    env_file:
      - ./config/
    environment:
      PORT: "3002"
      PROJETO_A_API_INTERNAL_URL: http://brmusic-api:8081
,